### ISSUE TITLE
quartz-0.4.1.zip is not a valid Grails plugin.

### ISSUE THREAD

**Issue by melaniespath** [nebolsin/grails-quartz#11]
OS: OSX 10.6.7
Java: 1.6.0_24
Grails 1.3.7

When I try to install the quartz plugin, the following happens:
melanie-spaths-macbook-pro-3:open-ehr-gen melaniespath$ grails install-plugin quartz
Welcome to Grails 1.3.7 - http://grails.org/
Licensed under Apache Standard License 2.0
Grails home is set to: /Library/grails-1.3.7

Base Directory: /Pablo_new/open-ehr-gen-framework-read-only/open-ehr-gen
Resolving dependencies...
Dependencies resolved in 1037ms.
Running script /Library/grails-1.3.7/scripts/InstallPlugin.groovy
Environment set to development
Resolving plugin quartz. Please wait...

Downloading: /Pablo_new/open-ehr-gen-framework-read-only/open-ehr-gen/lib/quartz-0.4.1.zip ...
Download complete.
Plugin /Users/melaniespath/.ivy2/cache/org.grails.plugins/quartz/zips/quartz-0.4.1.zip is not a valid Grails plugin. No plugin.xml descriptor found!

If you unzip the file at quartz-0.4.1.zip it forms

melanie-spaths-macbook-pro-3:zips melaniespath$ ls
__MACOSX        quartz-0.4.1        quartz-0.4.1.zip
melanie-spaths-macbook-pro-3:zips melaniespath$ ls quartz-0.4.1
LICENSE             grails-quartz-0.4.1.zip
Quartz.iml          lib
Quartz.ipr          plugin.xml
QuartzGrailsPlugin.groovy   scripts
application.properties      src
build.xml           test
docs                web-app
grails-app
melanie-spaths-macbook-pro-3:zips melaniespath$

The plugin.xml file is obviously there - does anyone else have this issue?

**Comment by atian25** [comment]
try this:
unzip quartz-0.4.1.zip
cd quartz-0.4.1
grails package-plugin

then u got a new zip, rename & install it

**Comment by nebolsin** [comment]
Quartz 0.4.2 is the latest stable release, please use it instead of 0.4.1.
